### ISSUE TITLE
[Feature] onMapRendered Callback

### ISSUE THREAD

**Issue by njovy** [note11g/flutter_naver_map#202]
Thank you so much for making this awesome plugin!

I have a suggestion and hope it's something you can add. Would it be possible to introduce an onMapRendered callback that kicks in once the map is fully rendered, rather than just when it's ready? The onMapReady is great for adding overlays but not that handy for snapshots.

I'm asking because I'd love a view-only widget that could load a cached snapshot for certain locations to boost performance. Flutter's platform view is cool but has its limits, so I'm looking at this as a workaround until the platform view is stable.

Also, waiting a few seconds before taking a screenshot isn't the best solution, especially with unpredictable network issues preventing map tiles from loading on time.

Thanks a lot for considering this. Please let me know if adding this callback is something you can do.

**Comment by note11g** [comment]
Thank you for your feedback and suggestion regarding the plugin.

I understand the need for an onMapRendered callback, particularly for tasks requiring precise timing, like taking snapshots. This feature would indeed be a significant enhancement to the plugin's functionality.

I want to clarify that the work on implementing an onMapLoaded event was conducted up until recently for the Android platform, facilitated by the support provided by the Naver Map SDK. This effort was relatively straightforward. However, implementing a similar feature for iOS proved challenging due to the absence of a comparable feature in the Naver Map SDK for iOS.

For those interested, my previous attempts and progress can be reviewed here: https://github.com/note11g/flutter_naver_map/tree/onMapLoaded. However, it's important to note that there are currently no ongoing efforts to further this functionality due to the encountered limitations. While this might come as a disappointment, I hope you understand that under the present conditions, advancing this feature for iOS is challenging.

I want to add that if the Naver team introduces support for this feature on iOS in the future, I am fully committed to implementing it on our end as well. Rest assured, any developments or updates in this regard will be promptly communicated.

Thank you for your support and for using the plugin. Your understanding and patience are greatly appreciated.
Have a Good Night!

**Comment by note11g** [comment]
+ and if you want to get map picture, see this function of naver map sdk [naver cloud, static map service](https://guide.ncloud-docs.com/docs/maps-static-api)

**Comment by njovy** [comment]
Really appreciate your quick response!

It's great to hear about the onMapLoaded event, especially for the Android platform. I might fork your repo to try out this callback since the iOS platform view is functioning well enough for my needs, and I might not need a workaround after all.

I also wasn't aware of the static map service offered by Naver Cloud. I'll definitely check it out. It sounds like a useful feature that could serve my purposes well.

Thanks again for your dedication to improving the plugin and for the informative update. I appreciate your efforts and the challenges involved, especially with platform-specific features. Keep up the great work 👍
